version: '3'
services:
  squid:
    image: "squid4"
    network_mode: bridge
    volumes:
      - "/srv/squid/cache:/var/cache/squid4" # assumed current dir contains browsers.json
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "$PWD/certs/myCA.pem:/local-mitm.pem:ro"
      - "$PWD/certs/myCA.crt:/local-mitm.crt:ro"
      - "$PWD/squid.conf:/etc/squid4/squid.conf"
      - "$PWD/proxychains.conf:/etc/proxychains.conf"
      - "$PWD/rewrite_url.py:/rewrite_url.py"
    links:
      - haproxy
    environment:
      - MITM_CERT=/local-mitm.crt
      - MITM_KEY=/local-mitm.pem
      - MITM_PROXY=yes
      - CONFIG_DISABLE=yes
      - PROXYCHAIN=yes
#      - PROXYCHAIN_TYPE=static_chain
#      - PROXYCHAIN_PROXY=http 172.17.0.1 8013
    ports:
      - "3128:3128"

  haproxy:
    image: "haproxy-selenoid"
    network_mode: bridge
    volumes:
      - "/var/log:/dev/log"
      - "$PWD:/usr/local/etc/haproxy"
      - "$PWD/certs/haproxy.pem:/etc/ssl/haproxy.pem:ro"
    ports:
      - "8013:8013"